### PR TITLE
Fluent Sequence Extensions 

### PR DESCRIPTION
**Pull request by thomasnield**
Hey @edvin, 

I know we are pretty occupied with TornadoFX but I needed a fluent API for working with JDBC, preferably with a `Sequence<ResultSet>`. I found your existing code to be pretty solid and didn't change much. I implemented `ParameterizedStatement` to have builder-like methods to return itself, as well as a method to return the `ResultSet` as a `Sequence<ResultSet>`. 

``` kotlin
data class Account(val id: Int, val name: String, val accountType: String)

val connection: Connection = DriverManager.getConnection("jdbc:sqlite:C:/Users/Thomas/OneDrive/Data/finance_rx.db")

connection.select("SELECT * FROM ACCOUNT WHERE ID = :id")
    .param("id",1)
    .asSequence()
    .map { Account(it.getInt("ID"), it.getString("NAME"), it.getString("ACCOUNT_TYPE")) }
    .forEach { println(it) }

```

### CODE REVIEW

**Comment by thomasnield** [comment]
Hmmmm... I don't think this automatically disposes Connection objects to release back to threadpools such as HikariCP. We'll need to think about that since RxJava-JDBC does that automatically, and it is quite elegant.

**Comment by edvin** [comment]
Hey! I'm away on a martial arts camp again this weekend, but I gave you commit rights, and will get up to speed when I get back on sunday evening, OK? Would be cool to get somewhere with this project as well :)

**Comment by thomasnield** [comment]
Okay sounds good. Thanks and have a good time!

**Comment by edvin** [comment]
The syntax changed (brutally) since this PR, so I'll close it, Thomas :)

**Pull request closed without merging**
