### PR TITLE
Added abstract 'columns' property to table

### PR DESCRIPTION
**Pull request by PvdBerg1998**

### CODE REVIEW

**Comment by edvin** [comment]
This isn't a good solution to the reflection problem because it adds boilerplate. A better approach would be to have definitions themselves actually add the columns to the columns list. Then we could keep the columns list `internal` as well.

**Comment by PvdBerg1998** [comment]
I'd still prefer more boilerplate over reflection, but if there is a cleaner way ... I'm trying to add the column to a list inside of the `Table.column` function, but I can't figure out how to get the instance out of the delegate.

**Comment by edvin** [comment]
You can, but unfortunately not until the property is accessed. Therefor I think we need to skip the delegate and use a function instead.

**Comment by edvin** [comment]
Great! This is the right move!

**Pull request merged**
